name: reselect
description: Efficiently derive data from your Redux Store
version: 0.3.0
homepage: https://github.com/brianegan/reselect_dart
author: Brian Egan <brian@brianegan.com>

environment:
  sdk: '>=2.0.0-dev.28.0 <3.0.0'

dependencies:
  memoize: ">=1.4.0 <2.0.0"

dev_dependencies:
  test: ^0.12.33
